# Generated by Django 2.1.2 on 2018-10-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='loaction',
            new_name='location',
        ),
    ]
