# Generated by Django 2.1.2 on 2018-10-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0002_auto_20181021_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='missing_pets_images'),
        ),
    ]
