# Generated by Django 2.1.2 on 2018-10-21 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0003_case_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='date',
            new_name='lost_date',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='location',
            new_name='lost_location',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='image',
            new_name='pet_image',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='name',
            new_name='pet_name',
        ),
        migrations.AddField(
            model_name='case',
            name='filed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='case',
            name='reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='user_address',
            field=models.CharField(default='home', max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='user_contact_no',
            field=models.IntegerField(default=0),
        ),
    ]
