# Generated by Django 2.1.2 on 2018-10-21 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0005_case_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reward',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='user_address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='user_contact_no',
            field=models.IntegerField(null=True),
        ),
    ]
