# Generated by Django 2.1.2 on 2018-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0006_auto_20181021_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
