# Generated by Django 2.1.2 on 2018-10-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0007_auto_20181021_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='pet_image',
            field=models.ImageField(default='default.jpg', upload_to='images_pets'),
        ),
    ]
