# Generated by Django 2.1.2 on 2018-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0008_auto_20181021_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='citizen_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='citizen_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='found_location',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='found_pet_image',
            field=models.ImageField(default='default.jpg', upload_to='images_pets'),
        ),
    ]
