# Generated by Django 2.1.2 on 2018-10-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0009_auto_20181025_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='found_status',
            field=models.BooleanField(default=False),
        ),
    ]
