# Generated by Django 2.1.2 on 2018-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0010_case_found_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='founder_id',
            field=models.IntegerField(null=True),
        ),
    ]
