# Generated by Django 2.1.2 on 2018-11-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0013_auto_20181026_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='confimred_status',
            field=models.BooleanField(default=False),
        ),
    ]
