# Generated by Django 2.1.2 on 2018-11-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0015_auto_20181104_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='found_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='lost_date',
            field=models.DateTimeField(null=True),
        ),
    ]
